# Publish all joint states
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 1000

# Control all joints
computed_torque_controller:
  type: "arm_control/CtcJointTrajectoryController"
  joints:
    - toe_foot_joint
    - foot_leg_joint
    - leg_arm_joint
    - arm_hand_joint
    - hand_finger_joint

  gains:
    toe_foot_joint: 
      pid: {p: 100.0, i: 0, d: 10.0}
    foot_leg_joint: 
      pid: {p: 30.0, i: 0, d: 4.0}
    leg_arm_joint: 
      pid: {p: 30.0, i: 0, d: 4.0}
    arm_hand_joint: 
      pid: {p: 100.0, i: 0, d: 10.0}
    hand_finger_joint: 
      pid: {p: 100.0, i: 0, d: 10.0}
